"use client"
import CountUp from "react-countup";

import Hero from "@/components/Hero";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import Link from "next/link"
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getDashboardStats } from "@/services/dashboardService";
import { getComplaints } from "@/services/complaintService";
import { getRecentActivity } from "@/services/activityService";
import ComplaintModal from "@/components/ComplaintModal";

import { motion } from "framer-motion"
import {
  Activity,
  CheckCircle,
  AlertTriangle,
  Brain,
  Clock3,
  ShieldCheck,
  LayoutDashboard,
  FileText,
  BarChart3,
  Sparkles,
  Settings
} from "lucide-react"

export default function Home() {
    const router = useRouter();
  const [stats, setStats] = useState({
  total: 0,
  pending: 0,
  inProgress: 0,
  resolved: 0,
  critical: 0,
});
const [selectedComplaint, setSelectedComplaint] = useState<any>(null);
const [isAnalysisOpen, setIsAnalysisOpen] = useState(false);
const [activities, setActivities] = useState<any[]>([]);
const [weeklyGrowth, setWeeklyGrowth] = useState(0);
const [resolvedGrowth, setResolvedGrowth] = useState(0);
const [recommendation, setRecommendation] = useState({
  title: "System Monitoring Active",
  message: "No urgent recommendation available yet.",
  level: "Low",
});
const [weeklyData, setWeeklyData] = useState([
  { day: "Mon", count: 0 },
  { day: "Tue", count: 0 },
  { day: "Wed", count: 0 },
  { day: "Thu", count: 0 },
  { day: "Fri", count: 0 },
  { day: "Sat", count: 0 },
  { day: "Sun", count: 0 },
]);
const activeComplaints = stats.pending + stats.inProgress;

const resolutionRate =
  stats.total > 0
    ? Math.round((stats.resolved / stats.total) * 100)
    : 0;

const criticalRate =
  stats.total > 0
    ? Math.round((stats.critical / stats.total) * 100)
    : 0;
    const projectedComplaints =
  stats.total > 0
    ? Math.ceil(stats.total * 1.08)
    : 0;
    const pendingRate =
  stats.total > 0
    ? Math.round((stats.pending / stats.total) * 100)
    : 0;

const systemHealth =
  stats.total > 0
    ? Math.max(0, 100 - pendingRate)
    : 100;
    const maxWeeklyCount = Math.max(
  ...weeklyData.map((item) => item.count),
  1
);
const exportCSV = async () => {
  try {
    const complaints = await getComplaints();

    const headers = [
      "Title",
      "Category",
      "Location",
      "Priority",
      "Status",
    ];

    const rows = complaints.map((complaint: any) => [
  `"${complaint.title}"`,
  `"${complaint.category}"`,
  `"${complaint.location}"`,
  `"${complaint.priority}"`,
  `"${complaint.status}"`,
]);
    const csvContent = [
      headers.join(","),
      ...rows.map((row: any) => row.join(",")),
    ].join("\n");

    const blob = new Blob([csvContent], {
      type: "text/csv;charset=utf-8;",
    });

    const url = URL.createObjectURL(blob);

    const link = document.createElement("a");

    link.href = url;
    link.download = "complaints.csv";

    document.body.appendChild(link);

    link.click();

    document.body.removeChild(link);
  } catch (error) {
    console.error(error);
  }
};
const exportPDF = async () => {
  try {
    const complaints = await getComplaints();

    const doc = new jsPDF();

    doc.setFontSize(20);
    doc.text("CivicAI Complaint Report", 14, 20);

    doc.setFontSize(11);
    doc.text(
      `Generated: ${new Date().toLocaleString()}`,
      14,
      30
    );
doc.setFontSize(12);

doc.text(
  `Total Complaints : ${complaints.length}`,
  14,
  38
);

doc.text(
  `Generated By : CivicAI Dashboard`,
  120,
  38
);
const resolved = complaints.filter(
  (c: any) => c.status === "Resolved"
).length;

const pending = complaints.filter(
  (c: any) => c.status === "Pending"
).length;

const critical = complaints.filter(
  (c: any) => c.priority === "High"
).length;

doc.text(`Resolved : ${resolved}`, 14, 46);
doc.text(`Pending : ${pending}`, 70, 46);
doc.text(`Critical : ${critical}`, 120, 46);
    autoTable(doc, {
  startY: 56,

  head: [["Title", "Category", "Location", "Priority", "Status"]],

  body: complaints.map((complaint: any) => [
    complaint.title,
    complaint.category,
    complaint.location,
    complaint.priority,
    complaint.status,
  ]),

  theme: "striped",

  headStyles: {
    fillColor: [14, 165, 233], // Cyan
    textColor: 255,
    fontStyle: "bold",
    halign: "center",
  },

  bodyStyles: {
    halign: "center",
  },

  alternateRowStyles: {
    fillColor: [245, 245, 245],
  },

  styles: {
    fontSize: 10,
    cellPadding: 3,
  },
});
doc.setFontSize(10);

doc.text(
  "Generated by CivicAI Dashboard",
  14,
  doc.internal.pageSize.height - 10
);
    doc.save("complaints-report.pdf");
  } catch (error) {
    console.error(error);
  }
};
const handleLogout = () => {
  localStorage.removeItem("token");
  router.push("/login");
};

useEffect(() => {
  const fetchStats = async () => {
    try {
      const data = await getDashboardStats();
      setStats(data);
      const complaints = await getComplaints();

setActivities(complaints.slice(0, 6));

const dayCounts = [
  { day: "Mon", count: 0 },
  { day: "Tue", count: 0 },
  { day: "Wed", count: 0 },
  { day: "Thu", count: 0 },
  { day: "Fri", count: 0 },
  { day: "Sat", count: 0 },
  { day: "Sun", count: 0 },
];

const now = new Date();

const currentDay = now.getDay();

const daysSinceMonday =
  currentDay === 0 ? 6 : currentDay - 1;

const startOfWeek = new Date(now);

startOfWeek.setDate(
  now.getDate() - daysSinceMonday
);

startOfWeek.setHours(0, 0, 0, 0);

const endOfWeek = new Date(startOfWeek);

endOfWeek.setDate(
  startOfWeek.getDate() + 7
);
const startOfPreviousWeek = new Date(startOfWeek);

startOfPreviousWeek.setDate(
  startOfWeek.getDate() - 7
);

const endOfPreviousWeek = new Date(startOfWeek);

const currentWeekComplaints = complaints.filter(
  (complaint: any) => {
    const date = new Date(complaint.createdAt);

    return (
      date >= startOfWeek &&
      date < endOfWeek
    );
  }
);

const previousWeekComplaints = complaints.filter(
  (complaint: any) => {
    const date = new Date(complaint.createdAt);

    return (
      date >= startOfPreviousWeek &&
      date < endOfPreviousWeek
    );
  }
);

const currentWeekResolved =
  currentWeekComplaints.filter(
    (complaint: any) =>
      complaint.status === "Resolved"
  ).length;

const previousWeekResolved =
  previousWeekComplaints.filter(
    (complaint: any) =>
      complaint.status === "Resolved"
  ).length;

const calculateGrowth = (
  current: number,
  previous: number
) => {
  if (previous === 0) {
    return current > 0 ? 100 : 0;
  }

  return Math.round(
    ((current - previous) / previous) * 100
  );
};

setWeeklyGrowth(
  calculateGrowth(
    currentWeekComplaints.length,
    previousWeekComplaints.length
  )
);

setResolvedGrowth(
  calculateGrowth(
    currentWeekResolved,
    previousWeekResolved
  )
);
complaints.forEach((complaint: any) => {
  const date = new Date(complaint.createdAt);

  if (
    date >= startOfWeek &&
    date < endOfWeek
  ) {
    const jsDay = date.getDay();

    const mondayIndex =
      jsDay === 0 ? 6 : jsDay - 1;

    dayCounts[mondayIndex].count += 1;
  }
});

setWeeklyData(dayCounts);
const activeItems = complaints.filter(
  (complaint: any) =>
    complaint.status !== "Resolved"
);

const highPriorityItems = activeItems.filter(
  (complaint: any) =>
    complaint.priority === "High"
);

const categoryCounts: Record<string, number> = {};

highPriorityItems.forEach((complaint: any) => {
  const category = complaint.category || "Other";

  categoryCounts[category] =
    (categoryCounts[category] || 0) + 1;
});

const topRiskCategory = Object.entries(categoryCounts)
  .sort((a, b) => b[1] - a[1])[0];

if (highPriorityItems.length >= 3 && topRiskCategory) {
  setRecommendation({
    title: "Immediate Priority Dispatch Suggested",
    message: `${topRiskCategory[0]} currently has ${topRiskCategory[1]} high-priority active complaint(s). Immediate field-team review is recommended.`,
    level: "High",
  });
} else if (activeItems.length >= 3) {
  setRecommendation({
    title: "Active Workload Requires Attention",
    message: `${activeItems.length} complaints are currently active. Review pending and in-progress cases to reduce operational backlog.`,
    level: "Medium",
  });
} else {
  setRecommendation({
    title: "Civic Operations Stable",
    message: `Current active workload is ${activeItems.length} complaint(s). No major escalation pattern is detected from the available complaint data.`,
    level: "Low",
  });
}
    } catch (error) {
      console.error("Failed to load dashboard stats:", error);
    }
  };

  fetchStats();
}, []);
  return (
    <main className="min-h-screen bg-[#020617] relative overflow-hidden">
      <div className="absolute inset-0 -z-10">
        <div className="absolute left-0 top-0 h-96 w-96 rounded-full bg-orange-500/10 blur-3xl" />
        <div className="absolute right-0 top-0 h-96 w-96 rounded-full bg-cyan-500/10 blur-3xl" />
        <div className="absolute bottom-0 left-1/2 h-96 w-96 -translate-x-1/2 rounded-full bg-blue-500/10 blur-3xl" />
      </div>

      <div className="mx-auto flex w-full max-w-[1700px] gap-6 px-4 py-6 lg:px-8">
        <aside className="hidden xl:block w-72 shrink-0">
  <div className="sticky top-6 rounded-3xl border border-slate-800 bg-slate-900/60 p-5 backdrop-blur-xl">

    <h2 className="text-lg font-bold text-white">
      CivicAI
    </h2>

    <div className="mt-8 space-y-2">

      <div className="group flex items-center gap-3 rounded-2xl border border-cyan-500/20 bg-cyan-500/10 px-4 py-4 text-cyan-400 transition-all duration-300 hover:translate-x-1 hover:border-cyan-400 hover:shadow-[0_0_30px_rgba(6,182,212,0.2)] shadow-[0_0_20px_rgba(6,182,212,0.15)]">
  <LayoutDashboard size={18} />
  <span>Dashboard</span>
</div>

      <Link
  href="/complaints"
  className="group flex items-center gap-3 rounded-2xl px-4 py-4 text-slate-400 transition-all duration-300 hover:translate-x-2 hover:bg-slate-800/60 hover:text-cyan-400 hover:shadow-[0_0_25px_rgba(34,211,238,0.12)]"
>
  <FileText
    size={18}
    className="transition-all duration-300 group-hover:text-cyan-400"
  />
  <span>Complaints</span>
</Link>

     <div className="flex items-center gap-3 rounded-xl px-4 py-3 text-slate-400 transition-all duration-300 hover:bg-slate-800/50 hover:text-white cursor-pointer">
  <Link
  href="/analytics"
  className="group flex items-center gap-3 rounded-2xl px-4 py-4 text-slate-400 transition-all duration-300 hover:translate-x-2 hover:bg-slate-800/60 hover:text-cyan-400 hover:shadow-[0_0_25px_rgba(34,211,238,0.12)]"
>
  <BarChart3
  size={18}
  className="transition-all duration-300 group-hover:text-cyan-400"
/>
  <span>Analytics</span>
</Link>
</div>

      <Link
  href="/ai-insights"
  className="group flex items-center gap-3 rounded-2xl px-4 py-4 text-slate-400 transition-all duration-300 hover:translate-x-1 hover:bg-slate-800/60 hover:text-white"
>
  <Sparkles size={18} />
  <span>AI Insights</span>
</Link>

      <Link
  href="/settings"
  className="group flex items-center gap-3 rounded-2xl px-4 py-4 text-slate-400 transition-all duration-300 hover:translate-x-1 hover:bg-slate-800/60 hover:text-white"
>
  <Settings size={18} />
  <span>Settings</span>
</Link>
<div className="mt-8 rounded-2xl border border-emerald-500/20 bg-slate-900/60 p-4">

  <p className="text-xs font-semibold uppercase tracking-[0.2em] text-emerald-400">
    System Status
  </p>

  <div className="mt-4 flex items-center gap-2">
    <div className="h-2 w-2 rounded-full bg-emerald-400 animate-pulse"></div>

    <span className="text-sm text-white">
      Online
    </span>
  </div>

  <div className="mt-5">

    <div className="mb-2 flex justify-between text-xs text-slate-400">
      <span>Storage</span>
      <span>78%</span>
    </div>

    <div className="h-2 rounded-full bg-slate-800 overflow-hidden">
      <div className="h-full w-[78%] rounded-full bg-cyan-400"></div>
    </div>

  </div>

  <div className="mt-5">

    <div className="mb-2 flex justify-between text-xs text-slate-400">
      <span>AI Engine</span>
      <span>94%</span>
    </div>

    <div className="h-2 rounded-full bg-slate-800 overflow-hidden">
      <div className="h-full w-[94%] rounded-full bg-emerald-400"></div>
    </div>

  </div>

  <div className="mt-5 rounded-xl bg-slate-950/60 p-3">

    <p className="text-xs text-slate-500">
      Active Complaints
    </p>

    <h3 className="mt-2 text-2xl font-bold text-cyan-400">
  <CountUp end={activeComplaints} duration={2} separator="," />
</h3>

  </div>

</div>

    </div>
  </div>
</aside>
<div className="flex-1">
        <header className="sticky top-4 z-30 flex items-center justify-between rounded-3xl border border-slate-800/80 bg-slate-900/70 px-5 py-4 backdrop-blur-2xl shadow-[0_10px_40px_rgba(0,0,0,0.25)]">
          <div>
            <h1 className="text-xl font-bold text-white">
              CivicAI Command Center
            </h1>
          </div>

          <div className="flex items-center gap-4">
            <div className="relative">

  <button className="flex h-12 w-12 items-center justify-center rounded-2xl border border-slate-700 bg-slate-900/60 transition hover:border-cyan-400 hover:bg-slate-800">

    🔔

  </button>

  <span className="absolute -right-1 -top-1 flex h-5 w-5 items-center justify-center rounded-full bg-red-500 text-xs font-bold text-white">
    3
  </span>

</div>
            <div className="text-right">
              <p className="text-sm font-semibold text-white">
                Faizal
              </p>

              <p className="text-xs text-slate-400">
                System Admin
              </p>
            </div>

            <div className="flex h-10 w-10 items-center justify-center rounded-full bg-orange-500 text-white font-bold">
              F
            </div>
            <button
  onClick={handleLogout}
  className="rounded-xl bg-red-500 px-4 py-2 text-sm font-semibold text-white hover:bg-red-600"
>
  Logout
</button>
          </div>
        </header>

        <motion.div
          initial={{ opacity: 0, y: 40 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.8 }}
          className="mt-12 mb-10"
        >
          <p className="text-sm uppercase tracking-[0.3em] text-slate-500">
            Civic Intelligence Platform
          </p>

          <h1 className="mt-4 text-4xl font-extrabold leading-tight tracking-tight text-white md:text-5xl xl:text-7xl">
            Smart Civic Complaint Management
          </h1>

          <p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300 md:text-xl">
  AI-powered monitoring, intelligent prioritization and real-time resolution
  tracking for smarter city operations. Built to help administrators monitor,
  analyze and resolve civic complaints efficiently.
</p>
          <section className="mt-8 flex flex-col gap-4 sm:flex-row sm:flex-wrap">

  <Link
  href="/create-complaint"
  className="rounded-2xl bg-cyan-500 px-6 py-3 font-semibold text-slate-950 transition hover:scale-105 hover:bg-cyan-400"
>
  + New Complaint
</Link>
  <button
  onClick={exportCSV}
  className="rounded-2xl border border-slate-700 bg-slate-900/60 px-6 py-3 font-semibold text-white transition hover:border-cyan-400"
>
  📊 Export Report
</button>
<button
  onClick={exportPDF}
  className="rounded-2xl border border-slate-700 bg-slate-900/60 px-6 py-3 font-semibold text-white transition hover:border-orange-400"
>
  📄 Export PDF
</button>

  <button
  onClick={() => setIsAnalysisOpen(true)}
  className="rounded-2xl border border-slate-700 bg-slate-900/60 px-6 py-3 font-semibold text-white transition hover:border-emerald-400"
>
  🤖 AI Analysis
</button>
  <button className="rounded-2xl border border-slate-700 bg-slate-900/60 px-6 py-3 font-semibold text-white transition hover:border-orange-400">
    ⚡ Live Monitor
  </button>

</section>
        </motion.div>

        <div className="mt-12 grid grid-cols-1 gap-6 md:grid-cols-2 xl:grid-cols-3">

  <motion.div
    initial={{ opacity: 0, y: 30 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.6, delay: 0.2 }}
    className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6 transition-all duration-300 hover:-translate-y-2 hover:border-cyan-400 hover:shadow-[0_0_40px_rgba(6,182,212,0.25)]"
  >
    <div className="flex items-center justify-between">
  <p className="text-sm text-slate-400">
    Total Complaints
  </p>

  <Activity size={20} className="text-cyan-400" />
</div>

    <h2 className="mt-3 text-5xl font-black tracking-tight text-white">
  <CountUp end={stats.total} duration={2} separator="," />
</h2>

    <p
  className={`mt-2 text-sm ${
    weeklyGrowth > 0
      ? "text-green-400"
      : weeklyGrowth < 0
      ? "text-red-400"
      : "text-slate-400"
  }`}
>
  {weeklyGrowth > 0 ? "+" : ""}
  {weeklyGrowth}% vs previous week
</p>
  </motion.div>

  <div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6 transition-all duration-300 hover:-translate-y-2 hover:border-slate-700 hover:shadow-[0_20px_60px_rgba(0,0,0,0.35)]">
    <div className="flex items-center justify-between">
  <p className="text-sm text-slate-400">
    Resolved Issues
  </p>

  <CheckCircle size={20} className="text-emerald-400" />
</div>

    <h2 className="mt-3 text-5xl font-black tracking-tight text-white">
  <CountUp end={stats.resolved} duration={2} />
</h2>

    <p
  className={`mt-2 text-sm ${
    resolvedGrowth > 0
      ? "text-emerald-400"
      : resolvedGrowth < 0
      ? "text-red-400"
      : "text-slate-400"
  }`}
>
  {resolvedGrowth > 0 ? "+" : ""}
  {resolvedGrowth}% vs previous week
</p>
  </div>

  <div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6 transition-all duration-300 hover:-translate-y-2 hover:border-slate-700 hover:shadow-[0_20px_60px_rgba(0,0,0,0.35)]">
    <div className="flex items-center justify-between">
  <p className="text-sm text-slate-400">
    Critical Alerts
  </p>

  <AlertTriangle size={20} className="text-orange-400" />
</div>

    <h2 className="mt-3 text-5xl font-black tracking-tight text-white">
  <CountUp end={stats.critical} duration={2} />
</h2>

    <p className="mt-2 text-sm text-orange-400">
      Needs attention
    </p>
  </div>

</div>

 <section className="mt-12">
  <div className="mb-6">
  <p className="text-sm uppercase tracking-[0.3em] text-slate-500">
    Live Monitoring
  </p>

  <h2 className="mt-2 text-3xl font-bold text-white">
    Recent Civic Complaints
  </h2>
</div>

  <div className="mt-6 grid grid-cols-1 gap-6 lg:grid-cols-2">

    {activities.map((activity: any, index: number) => (
  <motion.div
    key={activity._id}
    initial={{ opacity: 0, y: 30 }}
    animate={{ opacity: 1, y: 0 }}
    transition={{ duration: 0.5, delay: index * 0.1 }}
    onClick={() => setSelectedComplaint(activity)}
    className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6 transition-all duration-300 hover:-translate-y-2 hover:border-cyan-400 hover:shadow-[0_0_35px_rgba(34,211,238,0.15)]"
  >
    
    <div className="flex items-center justify-between">

      <span
        className={`rounded-full px-3 py-1 text-xs font-semibold ${
          activity.priority === "High"
            ? "bg-red-500/20 text-red-400"
            : activity.priority === "Medium"
            ? "bg-orange-500/20 text-orange-400"
            : "bg-emerald-500/20 text-emerald-400"
        }`}
      >
        {activity.priority || "Normal"}
      </span>

      <span className="text-xs text-slate-500">
        {new Date(activity.createdAt).toLocaleDateString()}
      </span>

    </div>

    <h3 className="mt-5 text-xl font-bold text-white">
      {activity.title}
    </h3>

    <div className="mt-4 flex items-center justify-between">

      <span
        className={`rounded-full px-3 py-1 text-xs ${
          activity.status === "Resolved"
            ? "bg-emerald-500/20 text-emerald-400"
            : activity.status === "Pending"
            ? "bg-yellow-500/20 text-yellow-400"
            : "bg-cyan-500/20 text-cyan-400"
        }`}
      >
        {activity.status}
      </span>

      <span className="text-sm text-slate-400">
        Civic Complaint
      </span>

    </div>
  </motion.div>
))}

  </div>
</section>



<section className="mt-12">
  <div className="flex items-center gap-3">
  <span className="rounded-full border border-cyan-500/30 bg-cyan-500/10 px-3 py-1 text-xs font-semibold text-cyan-400">
    AI POWERED
  </span>

  <h2 className="text-3xl font-bold text-white">
    AI Insights Panel
  </h2>
</div>

    <div className="mt-6 grid gap-6 md:grid-cols-3">

    {/* System Health */}
    <motion.div
      whileHover={{ y: -8, scale: 1.02 }}
      transition={{ duration: 0.25 }}
      className="group rounded-3xl border border-cyan-500/20 bg-slate-900/60 p-6
                 transition-all duration-300
                 hover:border-cyan-400/70
                 hover:shadow-[0_0_35px_rgba(34,211,238,0.18)]"
    >
      <div className="flex items-center gap-2 text-slate-400 group-hover:text-cyan-300">
        <Brain size={18} className="text-cyan-400" />
        <p>System Health</p>
      </div>

      <h3 className="mt-3 text-5xl font-black tracking-tight text-cyan-400">
        <CountUp end={systemHealth} duration={2} />%
      </h3>
    </motion.div>

    {/* Active Complaints */}
    <motion.div
      whileHover={{ y: -8, scale: 1.02 }}
      transition={{ duration: 0.25 }}
      className="group rounded-3xl border border-emerald-500/20 bg-slate-900/60 p-6
                 transition-all duration-300
                 hover:border-emerald-400/70
                 hover:shadow-[0_0_35px_rgba(52,211,153,0.18)]"
    >
      <div className="flex items-center gap-2 text-slate-400 group-hover:text-emerald-300">
        <Clock3 size={18} className="text-emerald-400" />
        <p>Active Complaints</p>
      </div>

      <h3 className="mt-3 text-5xl font-black tracking-tight text-emerald-400">
        <CountUp end={activeComplaints} duration={2} />
      </h3>
    </motion.div>

    {/* Risk Level */}
    <motion.div
      whileHover={{ y: -8, scale: 1.02 }}
      transition={{ duration: 0.25 }}
      className="group rounded-3xl border border-orange-500/20 bg-slate-900/60 p-6
                 transition-all duration-300
                 hover:border-orange-400/70
                 hover:shadow-[0_0_35px_rgba(251,146,60,0.18)]"
    >
      <div className="flex items-center gap-2 text-slate-400 group-hover:text-orange-300">
        <ShieldCheck size={18} className="text-orange-400" />
        <p>Risk Level</p>
      </div>

      <h3 className="mt-3 text-5xl font-black tracking-tight text-orange-400">
        {criticalRate >= 50
          ? "High"
          : criticalRate >= 20
          ? "Medium"
          : "Low"}
      </h3>
    </motion.div>

  </div>
</section>
<section className="mt-12">
  <div className="rounded-3xl border border-emerald-500/20 bg-gradient-to-br from-emerald-500/10 to-cyan-500/5 p-6 backdrop-blur-xl">

    <div className="flex items-center gap-3">
      <div className="h-3 w-3 rounded-full bg-emerald-400 animate-pulse" />

      <p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-400">
  Smart Recommendation · {recommendation.level} Priority
</p>
    </div>

    <h3 className="mt-4 text-2xl font-bold text-white">
  {recommendation.title}
</h3>

<p className="mt-3 max-w-3xl text-slate-300">
  {recommendation.message}
</p>

  </div>
</section>
 <section className="mt-12">
  <div className="mb-6">
    <p className="text-sm uppercase tracking-[0.3em] text-slate-500">
      Analytics
    </p>

    <h2 className="mt-2 text-3xl font-bold text-white">
  Current Week Complaint Trend
</h2>
  </div>

  <div className="rounded-3xl border border-slate-800 bg-slate-900/60 p-6">
  <div className="flex h-64 items-end justify-between gap-4">

    {weeklyData.map((item, index) => {
      const height =
        item.count === 0
          ? 8
          : Math.max(
              20,
              (item.count / maxWeeklyCount) * 220
            );

      return (
        <motion.div
          key={item.day}
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{
            duration: 0.4,
            delay: index * 0.08,
          }}
          className="group flex flex-1 flex-col items-center gap-2"
        >
          <span className="text-sm font-semibold text-cyan-400">
            {item.count}
          </span>

          <motion.div
            initial={{ height: 0 }}
            animate={{ height }}
            transition={{
              duration: 0.8,
              delay: index * 0.08,
            }}
            className="w-full max-w-12 rounded-t-xl bg-cyan-500
                       transition-all duration-300
                       group-hover:bg-cyan-400
                       group-hover:shadow-[0_0_25px_rgba(34,211,238,0.45)]"
          />

          <span className="text-xs text-slate-400">
            {item.day}
          </span>
        </motion.div>
      );
    })}

  </div>
</div>
</section>
<section className="mt-12 grid gap-6 md:grid-cols-3">

  <div className="rounded-3xl border border-cyan-500/20 bg-slate-900/60 p-6 transition hover:scale-[1.02] hover:border-cyan-300 hover:shadow-[0_0_60px_rgba(6,182,212,0.35)]">

    <p className="text-sm text-slate-400">
      Tomorrow Prediction
    </p>

    <h2 className="mt-4 text-5xl font-bold text-cyan-400">
  <CountUp end={projectedComplaints} duration={2} />
</h2>

    <p className="mt-3 text-slate-400">
      Projected volume using current complaint trend
    </p>

  </div>

  <div className="rounded-3xl border border-emerald-500/20 bg-slate-900/60 p-6 transition hover:scale-[1.02] hover:border-emerald-400">

    <p className="text-sm text-slate-400">
      Resolution Rate
    </p>

    <h2 className="mt-4 text-5xl font-bold text-emerald-400">
  <CountUp end={resolutionRate} duration={2} />%
</h2>

    <p className="mt-3 text-slate-400">
      Based on resolved complaints
    </p>

  </div>

  <div className="rounded-3xl border border-orange-500/20 bg-slate-900/60 p-6 transition hover:scale-[1.02] hover:border-orange-400">

    <p className="text-sm text-slate-400">
      High Risk Areas
    </p>

    <h2 className="mt-4 text-5xl font-bold text-orange-400">
  <CountUp end={stats.critical} duration={2} />
</h2>

    <p className="mt-3 text-slate-400">
      High-priority complaints requiring attention
    </p>

  </div>

</section>

      </div>
      </div>
      {isAnalysisOpen && (
  <div
    className="fixed inset-0 z-[100] flex items-center justify-center bg-black/75 p-4 backdrop-blur-md"
    onClick={() => setIsAnalysisOpen(false)}
  >
    <motion.div
      initial={{ opacity: 0, scale: 0.92, y: 30 }}
      animate={{ opacity: 1, scale: 1, y: 0 }}
      transition={{ duration: 0.25 }}
      onClick={(e) => e.stopPropagation()}
      className="max-h-[90vh] w-full max-w-4xl overflow-y-auto rounded-3xl border border-cyan-500/20 bg-slate-950 p-6 shadow-[0_0_60px_rgba(34,211,238,0.15)] md:p-8"
    >
      {/* Modal Header */}
      <div className="flex items-start justify-between gap-4">
        <div>
          <p className="text-sm font-semibold uppercase tracking-[0.25em] text-cyan-400">
            Smart Analysis
          </p>

          <h2 className="mt-2 text-3xl font-bold text-white">
            Civic Intelligence Report
          </h2>

          <p className="mt-2 text-slate-400">
            Real-time analysis based on current complaint data.
          </p>
        </div>

        <button
          onClick={() => setIsAnalysisOpen(false)}
          className="rounded-xl border border-slate-700 bg-slate-900 px-4 py-2 text-white transition hover:border-red-400 hover:bg-red-500/10 hover:text-red-400"
        >
          ✕
        </button>
      </div>

      {/* Metrics */}
      <div className="mt-8 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
        <div className="rounded-2xl border border-cyan-500/20 bg-cyan-500/5 p-5">
          <p className="text-sm text-slate-400">
            Total Workload
          </p>

          <h3 className="mt-2 text-3xl font-black text-cyan-400">
            {stats.total}
          </h3>
        </div>

        <div className="rounded-2xl border border-emerald-500/20 bg-emerald-500/5 p-5">
          <p className="text-sm text-slate-400">
            Resolution Rate
          </p>

          <h3 className="mt-2 text-3xl font-black text-emerald-400">
            {resolutionRate}%
          </h3>
        </div>

        <div className="rounded-2xl border border-orange-500/20 bg-orange-500/5 p-5">
          <p className="text-sm text-slate-400">
            Critical Rate
          </p>

          <h3 className="mt-2 text-3xl font-black text-orange-400">
            {criticalRate}%
          </h3>
        </div>

        <div className="rounded-2xl border border-violet-500/20 bg-violet-500/5 p-5">
          <p className="text-sm text-slate-400">
            System Health
          </p>

          <h3 className="mt-2 text-3xl font-black text-violet-400">
            {systemHealth}%
          </h3>
        </div>
      </div>

      {/* Operational Analysis */}
      <div className="mt-6 grid gap-6 md:grid-cols-2">
        <div className="rounded-2xl border border-slate-800 bg-slate-900/60 p-6">
          <h3 className="text-xl font-bold text-white">
            Operational Status
          </h3>

          <div className="mt-5 space-y-4">
            <div className="flex items-center justify-between">
              <span className="text-slate-400">
                Active Complaints
              </span>

              <span className="font-bold text-cyan-400">
                {activeComplaints}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-slate-400">
                Pending
              </span>

              <span className="font-bold text-yellow-400">
                {stats.pending}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-slate-400">
                In Progress
              </span>

              <span className="font-bold text-blue-400">
                {stats.inProgress}
              </span>
            </div>

            <div className="flex items-center justify-between">
              <span className="text-slate-400">
                High Priority
              </span>

              <span className="font-bold text-orange-400">
                {stats.critical}
              </span>
            </div>
          </div>
        </div>

        {/* Recommendation */}
        <div className="rounded-2xl border border-emerald-500/20 bg-gradient-to-br from-emerald-500/10 to-cyan-500/5 p-6">
          <p className="text-sm font-semibold uppercase tracking-[0.2em] text-emerald-400">
            {recommendation.level} Priority Recommendation
          </p>

          <h3 className="mt-4 text-xl font-bold text-white">
            {recommendation.title}
          </h3>

          <p className="mt-3 leading-7 text-slate-300">
            {recommendation.message}
          </p>
        </div>
      </div>

      {/* Footer */}
      <div className="mt-8 flex justify-end">
        <button
          onClick={() => setIsAnalysisOpen(false)}
          className="rounded-xl bg-cyan-500 px-6 py-3 font-semibold text-slate-950 transition hover:bg-cyan-400"
        >
          Close Analysis
        </button>
      </div>
    </motion.div>
  </div>
)}
     {selectedComplaint && (
  <ComplaintModal
    complaint={selectedComplaint}
    onClose={() => setSelectedComplaint(null)}

    onUpdated={(updatedComplaint) => {
      setActivities((prev) =>
        prev.map((activity) =>
          activity._id === updatedComplaint._id
            ? updatedComplaint
            : activity
        )
      );

      setSelectedComplaint(updatedComplaint);
    }}

    onDeleted={(deletedId) => {
      setActivities((prev) =>
        prev.filter(
          (activity) => activity._id !== deletedId
        )
      );

      setSelectedComplaint(null);

      setStats((prev) => ({
        ...prev,
        total: Math.max(0, prev.total - 1),
      }));
    }}
  />
)}
    </main>
  )
}